/**
 * WebForge Activate Project Tool
 *
 * Called by Hermes when entering a project folder for the first time.
 *
 * Checks if .webforge/memory/ exists:
 *   - If YES → project is already activated. Returns "ACTIVATED".
 *   - If NO  → returns "NOT_ACTIVATED" and tells Hermes to ask the user:
 *     - "New project" → creates .webforge/ structure + signals documentation dept to scan
 *     - "Subfolder of X" → creates a .webforge-subfolder marker file pointing to parent
 *
 * Place in: tool/activate_project.ts (auto-discovered by OpenCode)
 */

export default {
  description: "Check if this project is activated (has .webforge/ memory). If not activated, ask the user if this is a new project or a subfolder of an existing project. This is the FIRST thing Hermes does when entering any folder.",
  args: {
    action: {
      type: "string",
      description: "Action: 'check' (default) or 'activate_new' or 'mark_subfolder'",
      optional: true,
    },
    parent_project_path: {
      type: "string",
      description: "For 'mark_subfolder': the path to the parent project that has memory.",
      optional: true,
    },
  },
  async execute(args, context) {
    const fs = await import("fs")
    const path = await import("path")

    const action = args.action || "check"
    const cwd = process.cwd()
    const webforgeDir = path.join(cwd, ".webforge")
    const memoryDir = path.join(webforgeDir, "memory")
    const subfolderMarker = path.join(cwd, ".webforge-subfolder")

    // ─── CHECK: is this project activated? ───
    if (action === "check") {
      // Check for subfolder marker first
      if (fs.existsSync(subfolderMarker)) {
        const parentPath = fs.readFileSync(subfolderMarker, "utf-8").trim()
        return `SUBFOLDER: This folder is a subfolder of ${parentPath}. Use the parent project's memory at ${parentPath}/.webforge/memory/. Do not create separate memory here.`
      }

      // Check for existing memory
      if (fs.existsSync(memoryDir) && fs.existsSync(path.join(memoryDir, "STATE.md"))) {
        return `ACTIVATED: This project is already activated. Read .webforge/memory/STATE.md and .webforge/PROJECT.md to understand the project. Read .webforge/memory/work-log.md to see recent activity.`
      }

      return `NOT_ACTIVATED: This folder has no WebForge memory. Ask the user: "Is this a new project, or is it a subfolder of an existing WebForge project?" Then call activate_project with action='activate_new' or action='mark_subfolder' with the parent path.`
    }

    // ─── ACTIVATE_NEW: create the .webforge/ structure ───
    if (action === "activate_new") {
      if (fs.existsSync(memoryDir)) {
        return `ALREADY_ACTIVATED: .webforge/ already exists. Use action='check'.`
      }

      // Create directory structure
      fs.mkdirSync(webforgeDir, { recursive: true })
      fs.mkdirSync(memoryDir, { recursive: true })
      fs.mkdirSync(path.join(memoryDir, "decisions"), { recursive: true })
      fs.mkdirSync(path.join(memoryDir, "research"), { recursive: true })
      fs.mkdirSync(path.join(webforgeDir, "areas"), { recursive: true })
      fs.mkdirSync(path.join(webforgeDir, "mailbox"), { recursive: true })
      fs.mkdirSync(path.join(webforgeDir, "status"), { recursive: true })
      fs.mkdirSync(path.join(webforgeDir, "repo-agents"), { recursive: true })

      // Create initial STATE.md
      const stateContent = `# Project State

## Status
**Activated:** ${new Date().toISOString()}

## Current Phase
Project initialization — intelligence department scanning codebase

## What's Done
- [ ] Project activated
- [ ] Intelligence scan complete
- [ ] Area documentation written
- [ ] PROJECT.md overview written
- [ ] First task assigned

## What's In Progress
- Waiting for intelligence department to scan the codebase

## What's Blocked
(none)
`
      fs.writeFileSync(path.join(memoryDir, "STATE.md"), stateContent, "utf-8")

      // Create empty work-log.md
      fs.writeFileSync(
        path.join(memoryDir, "work-log.md"),
        "# WebForge Work Log\n\n> Auto-generated by activate_project. Every agent action is logged here.\n\n",
        "utf-8"
      )

      // Create empty constraints.md, errors-and-fixes.md, preferences.md
      fs.writeFileSync(
        path.join(webforgeDir, "constraints.md"),
        "# Project Constraints\n\n> Real-world constraints discovered during intelligence scan.\n\n",
        "utf-8"
      )
      fs.writeFileSync(
        path.join(webforgeDir, "errors-and-fixes.md"),
        "# Errors and Fixes\n\n> Every error encountered + how it was fixed. Auto-appended by safe_edit/safe_bash.\n\n",
        "utf-8"
      )
      fs.writeFileSync(
        path.join(webforgeDir, "preferences.md"),
        "# Developer Preferences\n\n> Accumulated preferences stated by the CEO. Not area-specific.\n\n",
        "utf-8"
      )

      // Create empty plan.md
      fs.writeFileSync(
        path.join(webforgeDir, "plan.md"),
        "# Project Plan\n\n> Updated by Hermes via the update_plan tool. The Ralph Loop checks for '## PROJECT COMPLETE'.\n\n## Tasks\n\n- [ ] Intelligence scan\n- [ ] Documentation\n- [ ] Build\n\n## PROJECT COMPLETE\n\n(Remove this line when complete — the Ralph Loop stops when it sees '## PROJECT COMPLETE')\n",
        "utf-8"
      )

      // Copy agents.json from global template if it exists
      const globalConfigDir = path.join(
        process.env.WEBFORGE_CONFIG_HOME || path.join(process.env.HOME || "", ".config", "webforge", "opencode"),
        ""
      )
      const templateAgentsJson = path.join(globalConfigDir, "project-template", "agents.json")

      // Try multiple locations for the template
      const possiblePaths = [
        templateAgentsJson,
        path.join(__dirname, "..", "project-template", "agents.json"),
        path.join(process.env.HOME || "", ".config", "webforge", "opencode", "project-template", "agents.json"),
      ]

      let agentsJsonCopied = false
      for (const p of possiblePaths) {
        try {
          if (fs.existsSync(p)) {
            fs.copyFileSync(p, path.join(webforgeDir, "agents.json"))
            agentsJsonCopied = true
            break
          }
        } catch {}
      }

      if (!agentsJsonCopied) {
        // Create minimal agents.json
        fs.writeFileSync(
          path.join(webforgeDir, "agents.json"),
          JSON.stringify({ agents: [] }, null, 2),
          "utf-8"
        )
      }

      return `ACTIVATED: Created .webforge/ structure. Now delegate to Athena (Intelligence) to scan the codebase. Intelligence will write findings to .webforge/memory/research/. Then Documentation department will write area docs to .webforge/areas/ and PROJECT.md.`
    }

    // ─── MARK_SUBFOLDER: create the marker file ───
    if (action === "mark_subfolder") {
      if (!args.parent_project_path) {
        return `BLOCKED: Must provide parent_project_path for mark_subfolder action.`
      }

      // Verify the parent has .webforge/memory/
      const parentMemory = path.join(args.parent_project_path, ".webforge", "memory")
      if (!fs.existsSync(parentMemory)) {
        return `BLOCKED: Parent project at ${args.parent_project_path} does not have .webforge/memory/. Are you sure it's a WebForge project?`
      }

      // Create the marker file
      fs.writeFileSync(
        subfolderMarker,
        args.parent_project_path,
        "utf-8"
      )

      return `MARKED: This folder is now marked as a subfolder of ${args.parent_project_path}. WebForge will use the parent's memory. You will not be asked again.`
    }

    return `Unknown action: ${action}. Use 'check', 'activate_new', or 'mark_subfolder'.`
  },
}
